name       : java-service-wrapper
version    : 3.5.34
release    : 1
source     :
    - https://wrapper.tanukisoftware.com/download/3.5.34/wrapper_3.5.34_src.tar.gz : d5c8f2530bba5ac5d938b25ccd2aee30f577e518098ae964d25be41fe06d3db6
license    : GPL-2.0
component  : programming.java
summary    : Enables a Java Application to be run as a Windows Service or Unix Daemon
description: |
    The Java Service Wrapper makes very easy to install a Java Application as a daemon process on Unix systems. The Wrapper monitors a JVM (Java Virtual Machine) process and automatically restarts it if it that the JVM has crashed or hung. This process takes just a few seconds once the Wrapper has decided there is a problem. It also gives the ability to handle process priority. 
builddeps  :
    - apache-ant
    - openjdk-8-devel
rundeps  :
    - openjdk-8
setup      : |
    sed -i "build.xml" \
        -e "s:value=\"1.4\":value=\"1.7\":"
    sed -i "src/c/Makefile-linux-x86"*.make \
        -e "s|all: .*|all: init wrapper libwrapper.so|"
build      : |
    export JAVA_HOME="${JAVA_HOME:-/usr/lib/openjdk-8}"
    ant -Dbits="64" -Ddist.arch="x86" jar compile-c-unix
install    : |
    install -Dm0755 bin/wrapper       $installdir/usr/bin/java-service-wrapper
    install -Dm0644 lib/libwrapper.so $installdir/usr/lib/java-service-wrapper/libwrapper.so
    install -Dm0644 lib/wrapper.jar   $installdir/usr/share/java/wrapper-${pkgver}.jar
    install -Dm0644 doc/wrapper-community-license*.txt $installdir/usr/share/licenses/java-service-wrapper/LICENSE
    ln -s /usr/share/java/wrapper-3.5.34.jar $installdir/usr/share/java/wrapper.jar
